---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}-client
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "name" . }}-client
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ template "name" . }}-client
    release: {{ .Release.Name }}
